SPK_NAME = bacula-client
SPK_VERS = 11.0.6
SPK_REV = 1
SPK_ICON = src/bacula.png

DEPENDS = cross/bacula

MAINTAINER = S.Falco
DESCRIPTION = Bacula is an open source backup system.  This is the client part of Bacula.
DISPLAY_NAME = Bacula Client

HOMEPAGE = https://www.bacula.org/
LICENSE  = AGPLv3

SERVICE_SETUP = src/service-setup.sh
SSS_SCRIPT = src/dsm-control.sh
FWPORTS = src/${SPK_NAME}.sc

STARTABLE = yes
CHANGELOG = ""

include ../../mk/spksrc.spk.mk
